# Fuse Core Theme for Jekyll - Settings
# https://github.com/tsjensen/fuse-core

markdown: kramdown
permalink: pretty
exclude: ['README.*', 'LICENSE.txt']
sass:
    style: expanded


# CAUTION
# When modifying this file, take care to preserve the indentation. This is YAML ...

# Main Headline, name required, subtitle optional
name: Matteo Cavalleri
#subtitle:
subtitle: Quantum Mechanic

# Title attribute of HTML Page, uses 'name' from above if empty
title: Matteo Cavalleri, Quantum Mechanic

# Information for web crawlers / Google, all of them optional
# 'description' and 'keywords' simply set the corresponding meta tags,
# 'crawl' is the 'Robots' tag http://www.robotstxt.org/meta.html
robots:
    description: Matteo Cavalleri's Personal Website.
    keywords: matteo, cavalleri, cv
    crawl: index,follow

# website address when deployed, also given as canonical link
url: https://teowaits.github.io/ebusinesscard/

# The 'baseurl' is prepended to all website-internal links.
# 'baseurl' will often be '', but for a project page on gh-pages, it needs to be the project name.
# If not empty, be careful to keep the leading slash, and don't add a slash at the end.
#baseurl: ''
baseurl: '/ebusinesscard'

# Enable Google Analytics. Leave empty (just "ga:" with subitems commented out) to disable.
# In order to comply with EU cookie law, enable 'cookieconsent' to show a little popup asking users to acknowledge the GA cookies.
# Also, some places require you to anonymize the users' IPs, which can be enabled via 'anonymizeip' below. You normally want that.
# https://support.google.com/analytics/answer/2763052
#ga:
ga:
   # account: 'UA-120960520-1'
   # cookieconsent: true
   # anonymizeip: true

# Plausible.io Analytics (alternative to Google Analytics that does not need cookies -> no cookie consent required)
# A config setting is required in plausible to enable tracking of the outbound links. Details described here:
# https://plausible.io/docs/outbound-link-click-tracking
# Leave empty (just "plausible:" with subitems commented out) to disable.
#plausible:
plausible:
  #  domain: 'teowaits.github.io'


# A picture of you, square(!), at least 180x180 pixels, more is better. Recommended file size < 100 KB.
# Leave empty for generic placeholder image.
# You can use your GitHub image:
#avatar: "https://avatars0.githubusercontent.com/u/8897534"
avatar: "images/icons/Authorea_icon.png"
#avatar:


# All the social media and other sites that we want to link to. The 'show' flag determines if the link is shown.
# The order of this list controls the order of the links on the page. Feel free to add.
links:
  - email:
      name: Email
      show: true
      href: mailto:matteo@cavalleri.eu
      icon: fas fa-envelope
  - linkedin:
      name: LinkedIn
      show: true
      href: https://www.linkedin.com/in/teowaits/
      icon: fab fa-linkedin
  - orcid:
      name: Orcid
      show: true
      href: https://orcid.org/0000-0002-7925-928X
      icon: fab fa-orcid
  - authorea:
      name: Authorea
      show: true
      href: https://www.authorea.com/users/245948-matteo-cavalleri
      icon: /ebusinesscard/images/favicons/favicon-16x16.png
  - github:
      name: GitHub
      show: true
      href: https://github.com/teowaits
      icon: fab fa-github
  - bsky:
      name: BlueSky
      show: true
      href: https://bsky.app/profile/physicsteo.bsky.social
      icon: fas fa-cloud    
  - discord:
      name: Discord
      show: true
      href: https://discordapp.com/users/teowaits
      icon: fab fa-discord
  - mastodon:
      name: Mastodon
      show: true
      href: https://mastodon.online/@physicsteo
      icon: fab fa-mastodon
  - instagram:
      name: Instagram
      show: true
      href: https://instagram.com/teowaits
      icon: fab fa-instagram   
  - tumblr:
      name: Tumblr
      show: true
      href: https://churchesofbrooklyn.tumblr.com/
      icon: fab fa-tumblr
  - strava:
      name: Strava
      show: true
      href: https://www.strava.com/athletes/3751640/
      icon: fab fa-strava
  - facebook:
      name: Facebook
      show: false
      href: https://facebook.com/YOUR_FB_USERNAME
      icon: fab fa-facebook
  - flickr:
      name: Flickr
      show: false
      href: https://flickr.com/photos/YOUR_FLICKR_USERNAME
      icon: fab fa-flickr
  - steam:
      name: Steam
      show: false
      href: http://steamcommunity.com/id/YOUR_STEAM_CUSTOM_ID
      icon: fab fa-steam
  - soundcloud:
      name: Soundcloud
      show: false
      href: https://soundcloud.com/YOUR_SOUNDCLOUD_USERNAME
      icon: fab fa-soundcloud
  - lastfm:
      name: Last.fm
      show: false
      href: http://www.last.fm/user/YOUR_LASTFM_USERNAME
      icon: fab fa-lastfm
  - codepen:
      name: CodePen
      show: false
      href: https://codepen.io/YOUR_CODEPEN_USERNAME
      icon: fab fa-codepen
  - stackoverflow:
      name: Stack Overflow
      show: false
      href: https://stackoverflow.com/users/YOUR_SO_USERNAME/
      icon: fab fa-stack-overflow
  - reddit:
      name: Reddit
      show: false
      href: https://reddit.com/user/YOUR_REDDIT_USERNAME
      icon: fab fa-reddit
  - medium:
      name: Medium
      show: false
      href: https://medium.com/@YOUR_MEDIUM_USERNAME
      icon: fab fa-medium
  - blog:
      name: Blog
      show: false
      href: http://host.domain/your_blog
      icon: fas fa-book-open
  - publickey:
      name: PGP Key
      show: false
      href: https://pastebin.com/raw/YOUR_PUBLIC_KEY
      icon: fas fa-key


# Extra HTML which will be displayed below the links. Keep it short. Leave empty to disable.
#extra_html: 
#extra_html: >
 #   Any (multiline) text containing simple HTML,
 #   such as links or ... lorem ipsum.

#EOF
